#PBS -q huge
#PBS -l select=1:ncpus=8:mem=100gb
#PBS -l walltime=168:00:00
#PBS -N VHH_tm
#PBS -o /home/tanyang/workspace/ProtREM/log
#PBS -e /home/tanyang/workspace/ProtREM/log


cd /home/tanyang/workspace/ProtREM
source /home/tanyang/miniconda3/bin/activate /home/tanyang/miniconda3/envs/protssn

# protein=VHH_tm
# database=/home/tanyang/uniref100.fasta
evcouplings \
    -P output/proteingym_v1/$protein/$protein \
    -p $protein \
    -s data/proteingym_v1/aa_seq/$protein.fasta \
    -d $database \
    -b "0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9" \
    -n 5 \
    src/single_config_monomer.txt