#PBS -q huge
#PBS -l select=1:ncpus=8:mem=100gb
#PBS -l walltime=168:00:00
#PBS -N msa
#PBS -o /home/tanyang/workspace/ProSST-R/log
#PBS -e /home/tanyang/workspace/ProSST-R/log


# database=/home/tanyang/data/0dataset/MEER/MEER_0.5.fasta
# protein=BFP
# bitscore=0.1
python src/data/get_msa.py \
    --query_file data/case/aa_seq/"$protein".fasta \
    --bitscores $bitscore \
    --database $database \
    --output_dir jackhmmer_results/"$protein"_uniref100